### ISSUE TITLE
Evaluate Different WYSIWYG Editors

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/template-maker#19]
[CKEditor](http://ckeditor.com/) is good for now because it Just Works™ and has the "placeholder" plugin that is pretty valuable, but it's not necessarily the best choice. It would be good to evaluate some additional editors (free & paid) including:
- [CKEditor](http://ckeditor.com)
  - **Pros**
    - Free and Open Source
    - We are already using this
    - Very mature
    - Has the placeholder plugin which works pretty nicely
  - **Cons**
    - Kind of ugly
    - Super hard to customize/style
    - Writing additional plugins is [pretty scary](http://docs.ckeditor.com/#!/api)
- [TinyMCE](http://www.tinymce.com/)
  - **Pros**
    - Free and Open Source
  - **Cons**
    - Kind of ugly
    - Would need to write a custom placeholder/variable plugin
- [Redactor](http://imperavi.com/redactor/)
  - **Pros**
    - Easy to write custom plugin (see [this page](http://imperavi.com/redactor/examples/insert-html/))
  - **Cons**
    - Not free ($100)
    - Has some bugs (click "Initialize" a bunch [on this page](http://imperavi.com/redactor/examples/destroy/))
- [Froala](https://editor.froala.com/)
  - **Pros**
    - Adding custom plugins for the variable piece seems pretty straightforward, see [this for an example](https://editor.froala.com/examples/insert-html)
  - **Cons**
    - Not free ($80, free for open source/non-profit projects)
    - ~~"Limited support" for ie8. Need to do more research to understand what this means.~~ ie8 support was added as of 1.1.6.
- [wysihtml](http://wysihtml.com/) - Free and open source
  - **Pros**
    - Free and open source
  - **Cons**
    - Very limited documentation

Feel free to update the above with additional points

**Comment by bsmithgall** [comment]
@shellicious I would appreciate your input on this as well, please poke around and let me know what you think in terms of design/UI. 

CKEditor and TinyMCE both look like the most full-featured, but very difficult to customize/style. Redactor seems to be really nice in terms of support for copy/pasting from work/sanitizing HTML sensibly and looks to have a decent API. Froala could be pretty promising; it has pretty good documentation and seems pretty sensible. wysihtml looks kind of nice but seems pretty poorly documented.

**Comment by bsmithgall** [comment]
This also looks interesting for variables: http://vitalets.github.io/x-editable/docs.html#gettingstarted though the project looks a bit abandoned...

**Comment by hamhands** [comment]
Late to the party, but fwiw I think the best two are redactor and froala, and given that the former costs $, the latter is likely the winner. wysihtml looks really cool, but I don't know if it would be best for template maker as it looks almost...too hip? I think the interface might be particularly off-putting to the non developer types, especially given that the concept itself (i.e. of a thing that makes a thing) is hard for users to wrap their heads around.
