### ISSUE TITLE
Some templates not generating placeholders correctly

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/template-maker#43]
Last night's changes fixed the professional services contract template, but for some reason the same issue is coming up for documents based on the RFP template. 

![new](https://cloud.githubusercontent.com/assets/3640800/7049918/364f2262-ddd2-11e4-9354-84a9c37f84d2.gif)

**Comment by bsmithgall** [comment]
@hamhands This is a problem with the underlying template.
![screen shot 2015-04-08 at 2 34 17 pm](https://cloud.githubusercontent.com/assets/1957344/7052413/62b04a0a-ddfc-11e4-98e7-d8c102ba30b2.png)

**Comment by bsmithgall** [comment]
Those should be class="js-fr-placeholder" but they are "fr-variable". The placeholders just need to be deleted and replaced.

**Comment by hamhands** [comment]
Ohhhhhhh ok.
