### ISSUE TITLE
Website link to salad dressing commercial?

### ISSUE THREAD

**Issue by gsf** [codeforamerica/template-maker#46]
Project looks great but we were thrown off by this website link in the project description:
https://www.youtube.com/watch?v=sKhsy0e0lqk

**Comment by gsf** [comment]
![screenshot 2015-12-28 at 11 51 12](https://cloud.githubusercontent.com/assets/151913/12021968/50c5c3b0-ad59-11e5-841b-dc2fb5a1c488.png)

**Comment by bsmithgall** [comment]
Ha! Thanks @gsf this was a bit of an in-joke between us from much earlier this year. We ended up abandoning development on this project ([read more here](http://yinzforamerica.tumblr.com/post/117600409642/refocus)) in favor of different work ([github](https://github.com/codeforamerica/pittsburgh-purchasing-suite), [end of year report](https://docs.google.com/presentation/d/1Rw_nMTUQTbFxnq9x-uQIPGC0IdnwdWPB2yHVAY1mG0g/edit?usp=sharing))

**Comment by bsmithgall** [comment]
There's a few gifs of what the template maker looks like in [this blog post](http://yinzforamerica.tumblr.com/post/115120267218/march-dev-update) as well

**Comment by gsf** [comment]
Thanks for the info!
